/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gson.unknown.field.test;

import com.google.gson.Gson;

class Test {
    public String a;
}

public class App {
    public static Gson gson = new Gson();

    public static void main(String[] args) {
        Test test = gson.fromJson("{\"a\": 1, \"b\": 2}", Test.class);
        System.out.println(test.a);
    }
}
